import React from 'react'


class Body extends React.Component {
    render() {
        return (
            <div className='main-body-box'>
                <h5>Your fav game has an app!</h5>
                <div className='body-domiscan-box'>
                    <h1>DomiScan</h1>
                    <p>The most popular game in the Dominican Republic has an app
                        that can keep track of the players' scores and sum
                        them up for you!</p>

                    <h3>Origins</h3>
                    <p>In the Dominican Republic, many families and friends gather
                        together on weekends to relax and loss the stress
                        generated by work and life landing at a squared table;
                        four chairs and a box of good old dominoes.
                        The word DomiScan has two meanings:
                    </p>
                    <h5>"Domi"</h5>
                    <p>
                        The first part, "Domi", has two meanings: etnicity and purpose.
                        Domi refers to the Dominican Republic, a country that loves
                        to play Dominoes. And, the second meaning refers to the
                        game of Dominoes.
                    </p>
                    <h5>"Scan"</h5>
                    <p>
                        The second part, "Scan", refers to a technical feature of
                        the game. Instead of counting the resulting Dominoes
                        from a match, we will use our phone's camera to scan the
                        dominoes and let the app do all the counting for the players.
                    </p>
                </div>
                <div className='body-features-box'>
                    <h1>Features & Technology</h1>

                    <h4>Front-End: JavaScript</h4>
                    <p>-> React Native</p>
                    <p>-> Expo</p>

                    <h4>Back-End: Python</h4>
                    <p>-> Flask</p>
                    <p>-> Pandas</p>
                    <p>-> OpenCV</p>
                </div>
                <div className='body-about-box'>
                    <h1>About Us</h1>

                    <h4>Front-End Engineer</h4>
                    <p>Carlos Daniel Vilar Jimenez</p>

                    <h4>Back-End Engineers</h4>
                    <p>Luis Vargas</p>
                    <p>Tyler Stevens</p>
                </div>
            </div>
        )
    }
}

export default Body